### ISSUE TITLE
Support for "Digitale postzegel"

### ISSUE THREAD

**Issue by Reggino** [myparcelnl/api#43]
Could you please explain / describe the use of stamps ('Digitale postzegel') as presented here: https://blog.myparcel.nl/digitale-postzegel ? It looks as if ```shipment_weight``` should be passed to the API in some way... Can this be a bit elaborated? And is there a way to list the different weights with the associated prices for this type of shipping?

Thanks.

**Comment by janssenr** [comment]
### Create digital stamp shipments

**Request**

```
POST https://api.myparcel.nl/shipments HTTP/1.1
Content-Type:application/vnd.shipment+json;charset=utf-8
User-Agent: CustomApiCall/2
Authorization:basic eUVJV1hFc3ZhMkxPeWRvVlM1bDVVZVJwamJNdVZQQXJSUGhFVkpCYw==
{
  "data": {
    "shipments": [{
      "reference_identifier" : "FOO-DPZ-BAR-46",
      "recipient": {
        "cc": "NL",
        "region": "Zuid-Holland",
        "city": "Hoofddorp",
        "street": "Siriusdreef",
        "number": "66",
        "postal_code": "2132WT",
        "person": "Mr. Parcel",
        "phone": "0213030315",
        "email": "testing@myparcel.nl"
      },
      "options": {
        "package_type": 4,
        "label_description": "This is a digital stamp shipment!"
      },
      "physical_properties": {
        "weight": 30
      },
      "carrier": 1
    }
  ]}
}
```

**Response**

```
HTTP/1.1 200 OK
Content-Type:application/json;charset=utf-8
{
  "data": {
    "ids": [{
      "id": 39234953
    }]
  }
}
```

**Comment by EdieLemoine** [comment]
It has recently been added to the docs. You can find the example above at https://myparcelnl.github.io/api/#6_B_4

**Comment by reindert-vetter** [comment]
@Reggino @janssenr 
Do you want to be kept informed of new functionalities or do you just need help? You can contact us via our Slack channel:
https://join.slack.com/t/myparcel-dev/shared_invite/enQtNDkyNTg3NzA1MjM4LTM0Y2IzNmZlY2NkOWFlNTIyODY5YjFmNGQyYzZjYmQzMzliNDBjYzBkOGMwYzA0ZDYzNmM1NzAzNDY1ZjEzOTM
