### ISSUE TITLE
Outdated documentation for ShipmentOptions

### ISSUE THREAD

**Issue by LeonidasJP** [myparcelnl/api#48]
The ShipmentOptions-documentation at https://myparcelnl.github.io/api/#7_C seems to be outdated. When pushing a parcel with `delivery_remark` set, the parcel is refused with the message `data.shipments[0].options The property delivery_remark is not defined and the definition does not allow additional properties`.

Submitted ShipmentOptions object:
```json
"options": {
    "insurance": {
        "amount": 5000,
        "currency": "EUR"
    },
    "package_type": 1,
    "delivery_type": 2,
    "label_description": "Order Lorem Ipsum",
    "delivery_remark": "Opmerkingen voor aflevering"
},
```

Has the field `delivery_remark` been dropped?

**Comment by EdieLemoine** [comment]
Hi Leon,

You are correct, `delivery_remark` is not used in our API anymore. Is it a necessary feature? If so we could look into reimplementing it.

**Comment by LeonidasJP** [comment]
Hi Edie,

Thanks for the reply. It is not necessary to reimplement the feature, at least not for us.

To prevent any mix-ups in the future, could you remove the `delivery_remark` from the `ShipmentOption` definition? Or at least mark it as "No longer supported"?

For me as external developer, developing an integration with your API directly, is there a way to stay informed on changes made to the API? Thus allowing me to update the integration faster?

**Comment by reindert-vetter** [comment]
I have removed delivery_remark from the documentation.
There is no newsletter for the api now. You can subscribe to our general newsletter. You can also set up a watch in GitHub, so that you can follow every commit in this repository. At the start of 2019, we want to look at how we can involve partners in our partners.

**Comment by reindert-vetter** [comment]
@LeonidasJP Do you want to be kept informed of new functionalities or do you just need help? You can contact us via our Slack channel:
https://join.slack.com/t/myparcel-dev/shared_invite/enQtNDkyNTg3NzA1MjM4LTM0Y2IzNmZlY2NkOWFlNTIyODY5YjFmNGQyYzZjYmQzMzliNDBjYzBkOGMwYzA0ZDYzNmM1NzAzNDY1ZjEzOTM

**Comment by LeonidasJP** [comment]
Hi @reindert-vetter, Thanks for the invite, I just joined the Channel.
