### ISSUE TITLE
Make 'User-agent' an environment variable in the Postman collection

### ISSUE THREAD

**Issue by gvdhoven** [myparcelnl/api#51]
It would be helpful if we could change the 'User-agent' setting as a global environment variable in the postman collection.

**Comment by gvdhoven** [comment]
@reindert-vetter i can't open a pull request since the postman collection is hosted externally else i would have done it for you :)

**Comment by reindert-vetter** [comment]
Done

**Comment by reindert-vetter** [comment]
@Webunity Do you want to be kept informed of new functionalities or do you just need help? You can contact us via our Slack channel:
https://join.slack.com/t/myparcel-dev/shared_invite/enQtNDkyNTg3NzA1MjM4LTM0Y2IzNmZlY2NkOWFlNTIyODY5YjFmNGQyYzZjYmQzMzliNDBjYzBkOGMwYzA0ZDYzNmM1NzAzNDY1ZjEzOTM
