### ISSUE TITLE
Validation Error Codes

### ISSUE THREAD

**Issue by LeonidasJP** [myparcelnl/api#54]
Not all "Human Readable Error Messages" are safe to output to humans ;-) For example, when submitting a random parcel with invalid House Number and Postal Code (both "t"), I get the following response:
```json
  "errors":[{
    "3503": {"fields":["data.shipments[0].recipient.number"],"human":["data.shipments[0].recipient.number"]},
    "3505": {"fields":["data.shipments[0].recipient.postal_code"],"human":["data.shipments[0].recipient.postal_code"]}
  }],
  "message":"Shipment validation error"
```

Is it possible to:
- Make the "human" parameter actually readable by end-users (eg. "Invalid house number/Postal Code supplied")
- Extend the API-Docs with a chapter listing the Error Codes you provide, so external tools can act automatically based on the various error codes (marking input fields, generalising messages et cetera), or for debugging/support puroposes (easier to pinpoint what exactly is going wrong)

**Comment by reindert-vetter** [comment]
Thank you for your comment. You are absolutely right. I will discuss this internally.

**Comment by janssenr** [comment]
And please make the error the same format as (most) other errors, like:
```json
{
   "errors":[
      {
         "code":0,
         "fields":[
            "data.shipments[0].carrier",
            "data.shipments[0].carrier"
         ],
         "human":[
            "data.shipments[0].carrier Is missing and it is required",
            "data.shipments[0].carrier Does not have a value in the enumeration Array\n(\n    [0] => 1\n    [1] => 2\n)\n"
         ]
      }
   ],
   "message":"Failed validation against JSON-SCHEMA shipment\/post_shipments_request.json"
}
```

**Comment by reindert-vetter** [comment]
We have solved this today. We will update the api documentation soon. You will now receive errors in the following format:
```json
{
  "errors": [
    {
      "code": 0,
      "fields": [
        "data.shipments[0].carrier",
        "data.shipments[0].carrier"
      ],
      "human": [
        "data.shipments[0].carrier Is missing and it is required",
        "data.shipments[0].carrier Does not have a value in the enumeration Array\n(\n [0] => 1\n [1] => 2\n)\n"
      ]
    }
  ],
  "message": "Failed validation against JSON-SCHEMA shipment/post_shipments_request.json"
}
```

**Comment by reindert-vetter** [comment]
After problems we had to undo this.
It is unclear when we will release it again.

**Comment by tvb** [comment]
What is the status of this issue @reindert-vetter ?

```
{'errors': [{'code': 0, 'fields': [''], 'human': [' NULL value found, but an object is required']}], 'message': 'Failed validation against JSON-SCHEMA shipment/post_shipments_request.json'}
```

I received a not so helpful human readable error message and having trouble tracking the error down.

**Comment by RichardPerdaan** [comment]
Hi @tvb,

Thank you for posting your message, there were problems with the digital stamp yesterday. This is where the error may come from. Are you still getting this error or has it been resolved.

**Comment by reindert-vetter** [comment]
@tvb I will bring it back to the attention internally. However, that will not solve your specific problem. I think Richard is right. If your json format is incorrect you will get a similar error. Then we should give a better error.

**Comment by tvb** [comment]
@RichardPerdaan @reindert-vetter It turns out sending plain JSON as the payload is not what the API is expecting despite your documentation. I needed to send a stringyfied JSON instead.

As per your documentation:

> #### 1.C HTTP methods
>The API is REST(ful) and uses JSON as it's primary data exchange format. Communication with the API goes through HTTPS thereby insuring data confidentiality and integrity. Here is a list of all supported HTTP methods

Quite annoying to debug this. The error message did not help a bit.

Please update the documentation to reflect this fact.

**Comment by RichardPerdaan** [comment]
Hi @tvb,

Thank you for reporting that the solution has been found. We are going to make nice error message in the API.

In addition, we will also adjust the API documents.

**Comment by tvb** [comment]
@RichardPerdaan any ETA?

**Comment by RichardPerdaan** [comment]
Hi @tvb,

The adjustment is planned for the next sprint. 
When it is resolved I will report it here

**Comment by RichardPerdaan** [comment]
The way of displaying the error messages has improved, this is the reason that I will close the isseu
