### ISSUE TITLE
carrier

### ISSUE THREAD

**Issue by janssenr** [myparcelnl/api#64]
When creating a shipment you have to send "carrier" in the request.
When fetching a shipment you receive "carrier_id" in the response.
Why is there a difference?

https://myparcelnl.github.io/api/#6_E
In the documentation is says "carrier" but "carrier_id" is returned.

**Comment by RichardPerdaan** [comment]
Dear @Rob Janssen,
Thank you for sending this message.
I agree that it is not correct. We will equalize this in the future.
I will also adjust the api documentation.

As soon as this has been changed in the API, you will be contacted via the this issue
