### ISSUE TITLE
Documentation error for webhook (11.3.B)

### ISSUE THREAD

**Issue by gvdhoven** [myparcelnl/api#65]
Currently the [documentation](https://myparcelnl.github.io/api/#11_B_3) mentions:
```
[
  {
    "shipment_id": "25482412",
    "account_id": 7003,
    "shop_id": 1897,
    "status": 2,
    "barcode": "3SMYPA749883621"
  }
]
```

but it should read:
```
{
    "data": {
        "hooks": [
            {
                "shipment_id": "25482412",
                "account_id": 7003,
                "shop_id": 1897,
                "status": 2,
                "barcode": "3SMYPA749883621"
            }
        ]
    }
}
```

**Comment by reindert-vetter** [comment]
Thank you for your message. However, this is not an example of what a webhook looks like. This is an example of the object "Webhook Object". I add an extra description and now we show your example in the documentation.
