### ISSUE TITLE
Missing documentation: Shipment related Object Definitions

### ISSUE THREAD

**Issue by LeonidasJP** [myparcelnl/api#7]
Hi MyParcel,

The following Shipment related Object Definitions seem to be missing in your API documentation:
* PickupLocation
* PhysicalProperties

Can you tell me what the specifications are for these Objects?

**Comment by reindert-vetter** [comment]
Sorry that these options are not well defined

Here can find the json for a Pickup Location:
https://myparcelnl.github.io/api/#6_B_4
Below 'Create shipment with pickup location'

Physical Properties includes only the weight:
https://myparcelnl.github.io/api/#7_A_2
Below 'POST example international shipment'

Thanks for your contribution. We will soon customize this.

**Comment by reindert-vetter** [comment]
Added PickupLocation Object Definitions:
https://myparcelnl.github.io/api/#9
