### ISSUE TITLE
Verschillende foutmeldingen

### ISSUE THREAD

**Issue by sharkooon** [myparcelnl/api#78]
Wanneer ik de api call uitvoer voor het downloaden van meer dan 25 labels (Accept: application/vnd.shipment_label_link+json; charset=utf8) krijg ik wanneer ik de url open als eerste een foutmelding in json dat de pdf nog niet klaar staat (dat is prima, na een aantal seconden is dit wel gereed):
`
{"errors":[{"code":5100}],"message":"File not ready yet and\/or non-existent"}
`
hierbij moet "message" bij "code" komen te staan?

En als ik oude labels download bijvoorbeeld ouder dan 3 maand dan verschilt de json error namelijk
`
{"error":[{"status":422,"code":3746,"title":"Not allowed to download expired label","message":"Not allowed to download expired label"}]}
`

Dan is het ineens "error" ipv "errors".
Hier staat "message" wel bij "code" in de zelfde array.

Zou fijn zijn als hier 1 standaard in is zoiets als:
`
{"errors":[{"status":5100,"code":5100,"title":"File not ready yet and\/or non-existent","message":"File not ready yet and\/or non-existent"}]}
`

**Comment by reindert-vetter** [comment]
Je hebt gelijk. We hebben dit eerder groots opgepakt, maar toen gingen veel systemen stuk. We zullen dit met kleinere stappen moeten doen (te beginnen met jouw voorstel).

Ook besproken in https://github.com/myparcelnl/api/issues/54#issuecomment-443231114

**Comment by RichardPerdaan** [comment]
De manier van het tonen van de error berichten zijn de afgelopen jaren verbeterd, dit is dan ook de reden dat ik de isseu zal sluiten.
